# Generated by Django 5.2.7 on 2025-10-27 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AboutSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "subtitle",
                    models.CharField(
                        default="About Vishwakarma Mechfab",
                        help_text="Subtitle above the main title",
                        max_length=200,
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        default="Engineering Excellence Since 2010",
                        help_text="Main heading of the About section",
                        max_length=200,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="Main description paragraph about the company"
                    ),
                ),
                (
                    "feature_1_title",
                    models.CharField(
                        default="Certified Engineers",
                        help_text="Title for first feature",
                        max_length=100,
                    ),
                ),
                (
                    "feature_1_description",
                    models.TextField(
                        default="Licensed professional engineers with extensive industry experience",
                        help_text="Description for first feature",
                    ),
                ),
                (
                    "feature_2_title",
                    models.CharField(
                        default="Quality Assurance",
                        help_text="Title for second feature",
                        max_length=100,
                    ),
                ),
                (
                    "feature_2_description",
                    models.TextField(
                        default="ISO certified processes ensuring highest quality standards",
                        help_text="Description for second feature",
                    ),
                ),
                (
                    "feature_3_title",
                    models.CharField(
                        default="Latest Technology",
                        help_text="Title for third feature",
                        max_length=100,
                    ),
                ),
                (
                    "feature_3_description",
                    models.TextField(
                        default="State-of-the-art tools and software for optimal results",
                        help_text="Description for third feature",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Set to active to display this version on the website",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "About Section",
                "verbose_name_plural": "About Sections",
                "ordering": ["-updated_at"],
            },
        ),
    ]
