# Generated by Django 5.2.7 on 2025-10-27 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vmf_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Service",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Service title (e.g., 'Design & Engineering')",
                        max_length=100,
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        default="🔧",
                        help_text="Emoji icon for the service (e.g., 🔧, 🏭, 💡, 🔍, ⚡, 📊)",
                        max_length=10,
                    ),
                ),
                (
                    "description",
                    models.TextField(help_text="Detailed description of the service"),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="URL-friendly identifier (auto-generated from title)",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Uncheck to hide this service from the website",
                    ),
                ),
                (
                    "display_order",
                    models.IntegerField(
                        default=0,
                        help_text="Order in which services appear (lower numbers appear first)",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Service",
                "verbose_name_plural": "Services",
                "ordering": ["display_order", "title"],
            },
        ),
    ]
