# Generated by Django 5.2.7 on 2025-10-27 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vmf_app", "0002_service"),
    ]

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Project title (e.g., 'Industrial HVAC System')",
                        max_length=200,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        help_text="Project category (e.g., 'Industrial', 'Automotive', 'Energy')",
                        max_length=100,
                    ),
                ),
                (
                    "short_description",
                    models.TextField(
                        help_text="Brief description shown on project card (2-3 sentences max)",
                        max_length=250,
                    ),
                ),
                (
                    "full_description",
                    models.TextField(
                        help_text="Detailed description shown in modal/project page"
                    ),
                ),
                (
                    "image_url",
                    models.URLField(
                        help_text="URL to project image (Cloudinary or other hosting)",
                        max_length=500,
                    ),
                ),
                (
                    "client_name",
                    models.CharField(
                        blank=True, help_text="Client name (optional)", max_length=200
                    ),
                ),
                (
                    "completion_date",
                    models.CharField(
                        blank=True,
                        help_text="Completion date (e.g., 'January 2024', optional)",
                        max_length=100,
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        blank=True,
                        help_text="Project location (optional)",
                        max_length=200,
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="URL-friendly identifier (auto-generated from title)",
                        max_length=200,
                        unique=True,
                    ),
                ),
                (
                    "is_featured",
                    models.BooleanField(
                        default=False,
                        help_text="Check to show on homepage (top 3 featured projects appear)",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Uncheck to hide this project from website",
                    ),
                ),
                (
                    "display_order",
                    models.IntegerField(
                        default=0,
                        help_text="Order in which projects appear (lower numbers appear first)",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Project",
                "verbose_name_plural": "Projects",
                "ordering": ["display_order", "-created_at"],
            },
        ),
    ]
