# Generated by Django 5.2.7 on 2025-10-27 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vmf_app", "0003_project"),
    ]

    operations = [
        migrations.CreateModel(
            name="GalleryItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Title for the gallery item", max_length=200
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="Brief description (1-2 sentences)", max_length=300
                    ),
                ),
                (
                    "media_type",
                    models.CharField(
                        choices=[("image", "Image"), ("video", "Video")],
                        default="image",
                        help_text="Type of media (Image or Video)",
                        max_length=10,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("workshop", "Workshop"),
                            ("fabrication", "Fabrication"),
                            ("welding", "Welding"),
                            ("machinery", "Machinery"),
                            ("projects", "Projects"),
                            ("assembly", "Assembly"),
                            ("testing", "Testing"),
                            ("installation", "Installation"),
                            ("other", "Other"),
                        ],
                        default="workshop",
                        help_text="Category for filtering",
                        max_length=50,
                    ),
                ),
                (
                    "media_url",
                    models.URLField(
                        help_text="URL to image or video (Cloudinary, YouTube, etc.)",
                        max_length=500,
                    ),
                ),
                (
                    "thumbnail_url",
                    models.URLField(
                        blank=True,
                        help_text="Thumbnail URL (for videos, optional for images)",
                        max_length=500,
                    ),
                ),
                (
                    "is_featured",
                    models.BooleanField(
                        default=False,
                        help_text="Show on homepage gallery section (top 2 items)",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Uncheck to hide this item from gallery"
                    ),
                ),
                (
                    "display_order",
                    models.IntegerField(
                        default=0,
                        help_text="Order in gallery (lower numbers appear first)",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Gallery Item",
                "verbose_name_plural": "Gallery Items",
                "ordering": ["display_order", "-created_at"],
            },
        ),
    ]
