# Generated by Django 5.2.7 on 2025-10-28 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vmf_app", "0004_galleryitem"),
    ]

    operations = [
        migrations.AddField(
            model_name="galleryitem",
            name="media_file",
            field=models.FileField(
                blank=True,
                help_text="Upload image or video file directly (recommended for images)",
                null=True,
                upload_to="gallery/",
            ),
        ),
        migrations.AddField(
            model_name="galleryitem",
            name="thumbnail_file",
            field=models.ImageField(
                blank=True,
                help_text="Upload thumbnail image (for videos, optional for images)",
                null=True,
                upload_to="gallery/thumbnails/",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="image_file",
            field=models.ImageField(
                blank=True,
                help_text="Upload project image directly (recommended)",
                null=True,
                upload_to="projects/",
            ),
        ),
        migrations.AlterField(
            model_name="galleryitem",
            name="media_url",
            field=models.URLField(
                blank=True,
                help_text="External URL to image/video (Cloudinary, YouTube, etc.) - Leave blank if uploading file",
                max_length=500,
            ),
        ),
        migrations.AlterField(
            model_name="galleryitem",
            name="thumbnail_url",
            field=models.URLField(
                blank=True,
                help_text="External thumbnail URL (optional)",
                max_length=500,
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="image_url",
            field=models.URLField(
                blank=True,
                help_text="External image URL (Cloudinary, etc.) - Leave blank if uploading file",
                max_length=500,
            ),
        ),
    ]
