# Generated by Django 5.2.7 on 2025-10-28 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vmf_app", "0005_galleryitem_media_file_galleryitem_thumbnail_file_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="galleryitem",
            name="media_file",
        ),
        migrations.RemoveField(
            model_name="galleryitem",
            name="media_type",
        ),
        migrations.RemoveField(
            model_name="galleryitem",
            name="media_url",
        ),
        migrations.RemoveField(
            model_name="galleryitem",
            name="thumbnail_file",
        ),
        migrations.RemoveField(
            model_name="galleryitem",
            name="thumbnail_url",
        ),
        migrations.AddField(
            model_name="galleryitem",
            name="image_file",
            field=models.ImageField(
                blank=True,
                help_text="Upload gallery image directly (recommended)",
                null=True,
                upload_to="gallery/",
            ),
        ),
        migrations.AddField(
            model_name="galleryitem",
            name="image_url",
            field=models.URLField(
                blank=True,
                help_text="External image URL (Cloudinary, etc.) - Leave blank if uploading file",
                max_length=500,
            ),
        ),
        migrations.AlterField(
            model_name="galleryitem",
            name="title",
            field=models.CharField(
                help_text="Title for the gallery image", max_length=200
            ),
        ),
    ]
