# Generated by Django 5.2.7 on 2025-10-28 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vmf_app", "0006_remove_galleryitem_media_file_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="galleryitem",
            old_name="image_url",
            new_name="media_url",
        ),
        migrations.RemoveField(
            model_name="galleryitem",
            name="image_file",
        ),
        migrations.AddField(
            model_name="galleryitem",
            name="media_file",
            field=models.FileField(
                blank=True,
                help_text="Upload image file directly (recommended)",
                null=True,
                upload_to="gallery/",
            ),
        ),
        migrations.AddField(
            model_name="galleryitem",
            name="media_type",
            field=models.CharField(
                choices=[("image", "Image"), ("video", "Video")],
                default="image",
                help_text="Type of media (Image only)",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="galleryitem",
            name="thumbnail_file",
            field=models.ImageField(
                blank=True,
                help_text="Upload thumbnail (optional)",
                null=True,
                upload_to="gallery/thumbnails/",
            ),
        ),
        migrations.AddField(
            model_name="galleryitem",
            name="thumbnail_url",
            field=models.URLField(
                blank=True, help_text="Thumbnail URL (optional)", max_length=500
            ),
        ),
    ]
