# Generated by Django 5.2.7 on 2025-10-28 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vmf_app", "0007_rename_image_url_galleryitem_media_url_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContactInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "company_name",
                    models.CharField(
                        default="Vishwakarma Mechfab",
                        help_text="Company name",
                        max_length=200,
                    ),
                ),
                (
                    "tagline",
                    models.CharField(
                        default="Professional mechanical engineering and fabrication solutions for industrial excellence.",
                        help_text="Company tagline/description for footer",
                        max_length=200,
                    ),
                ),
                (
                    "address_line_1",
                    models.CharField(
                        default="Industrial Area",
                        help_text="Address line 1",
                        max_length=200,
                    ),
                ),
                (
                    "address_line_2",
                    models.CharField(
                        blank=True,
                        help_text="Address line 2 (optional)",
                        max_length=200,
                    ),
                ),
                (
                    "city",
                    models.CharField(
                        default="Gujarat", help_text="City", max_length=100
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        default="Gujarat", help_text="State", max_length=100
                    ),
                ),
                (
                    "country",
                    models.CharField(
                        default="India", help_text="Country", max_length=100
                    ),
                ),
                (
                    "pin_code",
                    models.CharField(
                        default="123456", help_text="PIN/ZIP code", max_length=20
                    ),
                ),
                (
                    "primary_phone",
                    models.CharField(
                        default="+91 98765 43210",
                        help_text="Primary phone number",
                        max_length=20,
                    ),
                ),
                (
                    "secondary_phone",
                    models.CharField(
                        blank=True,
                        help_text="Secondary phone number (optional)",
                        max_length=20,
                    ),
                ),
                (
                    "whatsapp_number",
                    models.CharField(
                        blank=True,
                        help_text="WhatsApp number (optional)",
                        max_length=20,
                    ),
                ),
                (
                    "primary_email",
                    models.EmailField(
                        default="info@vishwakarmamechfab.in",
                        help_text="Primary email address",
                        max_length=254,
                    ),
                ),
                (
                    "secondary_email",
                    models.EmailField(
                        blank=True,
                        help_text="Secondary email address (optional)",
                        max_length=254,
                    ),
                ),
                (
                    "website_url",
                    models.URLField(
                        default="vishwakarmamechfab.in", help_text="Website URL"
                    ),
                ),
                (
                    "facebook_url",
                    models.URLField(
                        blank=True, help_text="Facebook page URL (optional)"
                    ),
                ),
                (
                    "instagram_url",
                    models.URLField(
                        blank=True, help_text="Instagram profile URL (optional)"
                    ),
                ),
                (
                    "linkedin_url",
                    models.URLField(
                        blank=True, help_text="LinkedIn profile URL (optional)"
                    ),
                ),
                (
                    "whatsapp_url",
                    models.URLField(
                        blank=True, help_text="WhatsApp business URL (optional)"
                    ),
                ),
                (
                    "twitter_url",
                    models.URLField(
                        blank=True, help_text="Twitter profile URL (optional)"
                    ),
                ),
                (
                    "youtube_url",
                    models.URLField(
                        blank=True, help_text="YouTube channel URL (optional)"
                    ),
                ),
                (
                    "working_hours_weekdays",
                    models.CharField(
                        default="Mon - Sat: 9:00 AM - 6:00 PM",
                        help_text="Working hours for weekdays",
                        max_length=100,
                    ),
                ),
                (
                    "working_hours_weekend",
                    models.CharField(
                        default="Sunday: Closed",
                        help_text="Working hours for weekend",
                        max_length=100,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Set to active to use this contact information",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Contact Information",
                "verbose_name_plural": "Contact Information",
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="ContactSubmission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(help_text="Sender's name", max_length=200)),
                (
                    "email",
                    models.EmailField(
                        help_text="Sender's email address", max_length=254
                    ),
                ),
                (
                    "subject",
                    models.CharField(help_text="Message subject", max_length=300),
                ),
                ("message", models.TextField(help_text="Message content")),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, help_text="Sender's IP address", null=True
                    ),
                ),
                (
                    "user_agent",
                    models.TextField(
                        blank=True, help_text="Sender's browser information"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "New"),
                            ("read", "Read"),
                            ("replied", "Replied"),
                            ("archived", "Archived"),
                        ],
                        default="new",
                        help_text="Message status",
                        max_length=20,
                    ),
                ),
                (
                    "admin_notes",
                    models.TextField(
                        blank=True, help_text="Internal notes (not visible to sender)"
                    ),
                ),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                (
                    "read_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the message was first read",
                        null=True,
                    ),
                ),
                (
                    "replied_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the message was replied to",
                        null=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "Contact Submission",
                "verbose_name_plural": "Contact Submissions",
                "ordering": ["-submitted_at"],
            },
        ),
    ]
